### ISSUE TITLE
Crashes after opening a .csv file

### ISSUE THREAD

**Issue by chiggiddi** [QL-Win/QuickLook#504]
**Describe the bug**
Quicklook crashed after opening a .csv file.

**To Reproduce**
1. Go to File Explorer
2. Select a .csv file
3. Press space to open QuickLook
4. Shows .csv
5. QuickLook crashes

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1809]
 - QuickLook Version: [e.g. 3.6.4 from Windows Store]

**Enclosed file is the csv**
[speisekarte.zip](https://github.com/QL-Win/QuickLook/files/3221366/speisekarte.zip)

**Comment by xupefei** [comment]
I have just fixed an issue with CSV viewer. Can you try download either the latest (v3.6.5) .msi or .zip version and replace the CsvViewer DLL with this one: [QuickLook.Plugin.CsvViewer.zip](https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer-Native/files/3249265/QuickLook.Plugin.CsvViewer.zip)? It should no longer crash.

NB: The nightly build system is down at the moment so you can't download the Nightly version to test this fix.

**Comment by xupefei** [comment]
I will see this issue as fixed. If it still happens to you, please feel free to reopen it.

**Comment by jpweytjens** [comment]
I've tried the new `CsvViewer` but QuickLook still crashes for many csv files. Attached you can find an example file.

I'm running version 3.6.5 installed with the msi file on Windows 10 1903. Is there any more information or log that I can provide?

[postcodes.zip](https://github.com/QL-Win/QuickLook/files/3252780/postcodes.zip)

**Comment by chiggiddi** [comment]
Hi Paddy, 

this is Cheng. Unfortunately with the updated csv .dll it still crashes, especially when I try to maximize the window. Could you please look into it once again?

**Comment by xupefei** [comment]
Strange. I can open both files without any problem:

![image](https://user-images.githubusercontent.com/1687847/58897913-1eec5580-8702-11e9-9544-979fff527bd6.png)

@jpweytjens @chiggiddi, can you two paste the error log here? It located at `%APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log`.

**Comment by chiggiddi** [comment]
Hi Paddy this is the error log as requested:

========6/4/2019 13:29:23========
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

========6/4/2019 13:29:44========
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

========6/4/2019 13:30:33========
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

========6/4/2019 13:31:37========
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by jpweytjens** [comment]
After a reboot, I can't reproduce the crash. It seems I was to quick in saying the updated DLL didn't work.

The log file contains multiple entries of

```
========04/06/2019 16:00:59========
CsvHelper.BadDataException: You can ignore bad data by setting BadDataFound to null.
   at CsvHelper.CsvParser.Read()
   at QuickLook.Plugin.CsvViewer.CsvViewerPanel.LoadFile(String path)
   at QuickLook.Plugin.CsvViewer.Plugin.View(String path, ContextObject context)
   at QuickLook.ViewerWindow.<>c__DisplayClass5_0.<BeginShow>b__0()

========04/06/2019 16:58:57========
CsvHelper.BadDataException: You can ignore bad data by setting BadDataFound to null.
   at CsvHelper.CsvParser.Read()
   at QuickLook.Plugin.CsvViewer.CsvViewerPanel.LoadFile(String path)
   at QuickLook.Plugin.CsvViewer.Plugin.View(String path, ContextObject context)
   at QuickLook.ViewerWindow.<>c__DisplayClass5_0.<BeginShow>b__0()
```

**Comment by chiggiddi** [comment]
Also after reboot I still can replicate the same crash issue when trying to manually resize the window by dragging on the edges of the window in either x or y directions.
```
========6/4/2019 13:29:23========
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by xupefei** [comment]
@jpweytjens According to the RFC specification, CSV file has to use `,` as the separator. Also, note that "CSV" is short for "**Comma**-separated values" :)

@chiggiddi Your issue is not related to CSV file. Can you open a new issue so I can close this one?

**Comment by chiggiddi** [comment]
Yes sure will do!

**Comment by Loreno10** [comment]
@xupefei Looks like CSV problem is still a thing. I cannot seem to open any CSV. I have QuickLook from Windows Store.
Here's an error message:
![image](https://user-images.githubusercontent.com/10273406/64611588-1165fc00-d3d2-11e9-8518-f3d2d75b4b56.png)

I also attached a file I'm having problem with.
[equipment20190910090711196.zip](https://github.com/QL-Win/QuickLook/files/3595476/equipment20190910090711196.zip)

**Comment by xupefei** [comment]
@Loreno10 The issue is now fixed in the Nightly version only. Store version does not contain the fix.

**Comment by tiboine** [comment]
Uninstalled the store version. installed 3.6.5. Still crashes on csv files.
