### ISSUE TITLE
With Officeview plugin installed, Powerpoint preview doesn't work

### ISSUE THREAD

**Issue by cba321x** [QL-Win/QuickLook#648]
Firstly great software!

With the **officeview plugin installed**, the **Powerpoint preview doesn't work** but word preview is working. It comes up with a notification "Failed to preview [Powerpoint name]...".

Thanks!

**Comment by cba321x** [comment]
By the way, it's office 2019

**Comment by xupefei** [comment]
You have to install Office using an EXE installer. Office 365 from Windows Store is not supported by this plugin.

**Comment by cba321x** [comment]
It isn't installed from the Windows Store and the Word and Excel preview works, just issues with the Powerpoint.

**Comment by cba321x** [comment]
> You have to install Office using an EXE installer. Office 365 from Windows Store is not supported by this plugin.

Is there any way to solve this?

**Comment by markwu** [comment]
I have the same issue, too. It works well with word and excel, but not powerpoint.

I didn't install office 2019 from windows store.

**Comment by markwu** [comment]
Where can I find the error log? I can post it here.

**Comment by rabelux** [comment]
Actually I have to join in on this issue. All powerpoint pptx-files fail to preview with the little hint "consider reporting this..."
Using the OfficeViewer-Native with normal installation of office 365 (Win 7, so not store version).
Exception log says:
```
System.Runtime.InteropServices.COMException (0x80004005): Calling a COM-Component caused HRESULT E_FAIL-Error.
   bei QuickLook.Plugin.OfficeViewer.IPreviewHandler.DoPreview()
   bei QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   bei QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   bei QuickLook.ViewerWindow.<>c__DisplayClass7_0.<BeginShow>b__1()
```
(translated by me, so maye not look for the whole string on the internet)

**Comment by rabelux** [comment]
@xupefei would you suggest to use the non-native-plugin even though office is installed?

**Comment by markwu** [comment]
Any progress about this issue?

**Comment by rabelux** [comment]
My problem is fixed and previewing pptx-files works, although I did't do anything to tackle it. Are u using the native viewer or OfficeViewer v4? What does your error log show?

**Comment by markwu** [comment]
@rabelux No developer reply this issue, I suppose this bug still there. After testing again, it works. So, this issue could be closed! Thanks.
